#!/usr/bin/env bash
set -eu

# oyster setup script

REPOSITORY="https://github.com/ryuzi/oyster.git"
PREFIX_DEFAULT="${HOME:?}"
OYST_CONFIG="${PREFIX_DEFAULT}/.oyster/config"

# check config
{
    if [ -s "${OYST_CONFIG}" ]; then
        echo "> ${OYST_CONFIG} already exists!"
        echo
        echo "# ${OYST_CONFIG}"
        cat "${OYST_CONFIG}"
        echo
        exit 1
    fi
}

# check installation directory
{
    if [ -d "${PREFIX_DEFAULT}/.oyster" ]; then
        echo "> '${PREFIX_DEFAULT}/.oyster' already exists!"
        echo
        exit 1
    fi
    if [ -e "${PREFIX_DEFAULT}/.oyster/config" ]; then
        echo "> '${PREFIX_DEFAULT}/.oyster/config' already exists!"
        echo
        exit 1
    fi
}

# check git command
{
    if type git; then
        : # no problem.
    else
        echo "> please install git."
        echo
        exit 1
    fi
}

# download oyster
{
    cd "${PREFIX_DEFAULT}"
    mkdir .oyster
    git clone "${REPOSITORY}" .oyster/core
    cd -
}

# create initial setting
{
    echo "export OYST_PATH=${PREFIX_DEFAULT}/.oyster/core" >> "${OYST_CONFIG}"
    echo "export PATH=\$OYST_PATH:\$PATH" >> "${OYST_CONFIG}"
    echo
    echo "# ${OYST_CONFIG}"
    cat "${OYST_CONFIG}"
    echo
    echo "> initial setting for '${OYST_CONFIG}' created."
    echo
}

# write initial setting for .bashrc
echo "> please add the following settings for oyster to the top of your .bashrc file:"
{
    echo
    echo
    echo "# oyster script"
    echo "[ -s \"${OYST_CONFIG}\" ] && source \"${OYST_CONFIG}\""
    echo "# end oyster script"
    echo
    echo
}

echo "> complete setup oyster."
